source 'https://rubygems.org'

gem 'smashing'
gem 'mysql2'
gem 'twitter'
gem 'thin'
gem 'htmlentities'
gem 'rdf-rdfxml'
gem 'simple-rss'
gem 'httparty'
gem 'tiny_tds'
gem 'json'
gem 'passenger'
gem 'roo'
gem 'nokogiri'
gem 'google-api-client'
gem 'xml-simple'
gem 'puma'
